### PR TITLE
add async to dependencies

### PR DESCRIPTION
**Pull request by alessioalex**
@robertkowalski can you please merge this in and publish a new version on npm?

### CODE REVIEW

**Comment by robertkowalski** [comment]
+1

**Comment by robertkowalski** [comment]
added you as a collaborator, feel free to land on your own :)

**Comment by robertkowalski** [comment]
@alessioalex what is your npm username?

**Comment by alessioalex** [comment]
@robertkowalski alessioalex (just like on github && twitter)

**Comment by robertkowalski** [comment]
awesome, you can publish now @alessioalex  :)

**Comment by alessioalex** [comment]
thanks! published the new version to npm with the hotfix

**Pull request merged**
